[package]
name = "qdrant_fastembed_rm"
version = "0.1.0"
edition = "2021"

[dependencies]
fastembed = "3.11.1"
qdrant-client = "1.10.2"
serde_json = "1.0.120"
tokio = { version = "1", features = ["full"] }
