name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
          - 6334:6334
        options: --volume /home/runner/work/qdrant_fastembed_rm/qdrant_storage:/qdrant/storage

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
